#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# PyTeCK documentation build configuration file, created by
# sphinx-quickstart on Thu Apr 13 09:49:20 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import datetime
import os
import sys
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as get_version

sys.path.insert(0, os.path.abspath("../src"))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "nbsphinx",
]

# nbsphinx: use the outputs stored in the committed notebooks rather than
# re-executing them at build time (execution needs Cantera and takes minutes).
nbsphinx_execute = "never"

autodoc_default_options = {"members": True}
autoclass_content = "class"
napoleon_numpy_docstring = True
napoleon_google_docstring = False
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("http://docs.scipy.org/doc/numpy/", None),
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3.14", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "cantera": ("https://cantera.org/stable/", None),
    "tables": ("https://www.pytables.org/", None),
    "pyked": ("https://pr-omethe-us.github.io/PyKED/", None),
}

# Make the module index more useful by sorting on the module name
# instead of the package name
modindex_common_prefix = ["pyteck."]


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = {
    ".rst": "restructuredtext",
    #  '.txt': 'markdown',
    #  '.md': 'markdown',
}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "PyTeCK"
author = "Kyle E. Niemeyer"
this_year = datetime.date.today().year
copyright = "{}, {}".format(this_year, author)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
try:
    release = get_version("pyteck")
except PackageNotFoundError:
    release = "unknown"
# The short X.Y version.
version = ".".join(release.split(".")[:2])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "_graph"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# sphinxcontrib-bibtex (v2+) requires bib files to be declared here, and the
# citation style is set globally rather than per ``bibliography`` directive.
bibtex_bibfiles = ["refs.bib"]
bibtex_default_style = "unsrt"

# Suppress duplicate citation warnings. "ref.citation" covers the docutils-level
# warnings (and, as a side effect, undefined-citation and unused-reference
# warnings). "bibtex.duplicate_citation" covers a reference cited from more than
# one page-local bibliography (e.g., niemeyer:2015 appears in both theory and
# psr_theory); label collisions are already avoided via the bibliography
# directive's ``:labelprefix:``.
suppress_warnings = ["ref.citation", "bibtex.duplicate_citation"]


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "github_user": "pr-omethe-us",
    "github_repo": "PyTeCK",
    "github_banner": True,
    "github_button": True,
    "show_powered_by": True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "PyTeCKdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "PyTeCK.tex", "PyTeCK Documentation", author, "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "pyteck", "PyTeCK Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "PyTeCK",
        "PyTeCK Documentation",
        author,
        "PyTeCK",
        "Evaluation of chemical kinetic models with experimental data.",
        "Miscellaneous",
    ),
]
