package:
  name: pyteck
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - pyyaml >=5.1
    - numpy >=1.21
    - scipy >=1.7
    - pint >=0.20
    - pytables >=3.7
    - cantera >=3.0
    - pyked >=0.4.1

test:
  imports:
    - pyked
    - cantera

  requires:
    - pytest >=7.0
    - pytest-cov

  commands:
    - pytest -vv --pyargs pyteck

about:
  home: https://github.com/pr-omethe-us/PyTeCK
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Evaluation of chemical kinetic models with experimental data
  doc_url: https://kyleniemeyer.github.io/PyTeCK
  dev_url: https://github.com/pr-omethe-us/PyTeCK
